---
title: "p8105_hw5_xw2758"
author: "Xinyi Wang"
date: "11/18/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	fig.asp = 0.6,
	fig.width = 6,
	out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
homicide_df = 
  read_csv("homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```


Let's look at this a bit

```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

Try to iterate ........

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```



```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


# Problem 2

**1.create a dataframe containing all file names**

```{r}
filename_df = tibble( path = list.files("data/"))
filename_df
```

**2.Iterate over file names and read in data for each subject**

```{r}
 arm_df = filename_df %>% 
 mutate(
 path = str_c("data/", path),
 map_df(.x = path, read.csv)
 ) 
arm_df
```

**3.Tidy the result**

```{r}
arm_df_tidy = 
  arm_df %>%
  mutate(
    path = str_remove_all(path,".csv"),
    path = str_remove_all(path, "data/")
  ) %>%
  separate(path, into = c("arm","id"), sep = 3) %>%
  mutate(
    id = str_remove_all(id, "_"),
    arm = str_replace(arm,"con","control"),
    arm = str_replace(arm,"exp","experiment")
  ) %>% 
 pivot_longer(
  week_1:week_8,
  names_prefix = "week_",
  names_to = "week",
  values_to = "value"
 )
arm_df_tidy
```

**4.Make a spaghetti plot**





# Problem 3

